const LOGIN = "LOGIN";
const NO_USERNAME = "NO_USERNAME";
const NO_PASSWORD = "NO_PASSWORD";
const LOADING_START = "LOADING_START";
const LOADING_END = "LOADING_END";

export {
    LOGIN,
    NO_USERNAME,
    NO_PASSWORD,
    LOADING_START,
    LOADING_END
}